//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanSuaEntities : DbContext
    {
        public QLBanSuaEntities()
            : base("name=QLBanSuaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblChiTietHDBanSua> TblChiTietHDBanSuas { get; set; }
        public virtual DbSet<TblHDBanSua> TblHDBanSuas { get; set; }
        public virtual DbSet<TblKhachHang> TblKhachHangs { get; set; }
        public virtual DbSet<TblLoaiSua> TblLoaiSuas { get; set; }
        public virtual DbSet<TblNhanVien> TblNhanViens { get; set; }
        public virtual DbSet<TblPhanLoai> TblPhanLoais { get; set; }
        public virtual DbSet<TblSua> TblSuas { get; set; }
        public virtual DbSet<TblTaiKhoan> TblTaiKhoans { get; set; }
    }
}
