//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChiTietHDBanSua
    {
        public string MaHDBan { get; set; }
        public string MaSua { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public double ThanhTien { get; set; }
    
        public virtual TblHDBanSua TblHDBanSua { get; set; }
        public virtual TblSua TblSua { get; set; }
    }
}
