//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHDBanSua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHDBanSua()
        {
            this.TblChiTietHDBanSuas = new HashSet<TblChiTietHDBanSua>();
        }
    
        public string MaHDBan { get; set; }
        public string MaNhanVien { get; set; }
        public System.DateTime NgayBan { get; set; }
        public string MaKhachHang { get; set; }
        public double TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChiTietHDBanSua> TblChiTietHDBanSuas { get; set; }
        public virtual TblKhachHang TblKhachHang { get; set; }
        public virtual TblNhanVien TblNhanVien { get; set; }
    }
}
